const data = [
  {
    num: "1",
    name: "big ball with a picture",
    count: "2",
    year: "1960",
    shape: "ball",
    color: "yellow",
    size: "big",
    favorite: false,
  },
  {
    num: "2",
    name: "Green ball with flowers",
    count: "5",
    year: "2000",
    shape: "ball",
    color: "green",
    size: "big",
    favorite: false,
  },
  {
    num: "3",
    name: "Red matte ball",
    count: "3",
    year: "1990",
    shape: "ball",
    color: "red",
    size: "big",
    favorite: false,
  },
  {
    num: "4",
    name: "Red Icicle",
    count: "2",
    year: "1980",
    shape: "figure",
    color: "red",
    size: "big",
    favorite: false,
  },
  {
    num: "5",
    name: "Red grapes",
    count: "4",
    year: "1980",
    shape: "figure",
    color: "red",
    size: "medium",
    favorite: true,
  },
  {
    num: "6",
    name: "Red ball with a picture",
    count: "6",
    year: "2010",
    shape: "ball",
    color: "red",
    size: "big",
    favorite: false,
  },
  {
    num: "7",
    name: "Milky white ball",
    count: "12",
    year: "1960",
    shape: "ball",
    color: "white",
    size: "medium",
    favorite: true,
  },
  {
    num: "8",
    name: "Red ball",
    count: "10",
    year: "2010",
    shape: "ball",
    color: "red",
    size: "big",
    favorite: false,
  },
  {
    num: "9",
    name: "Old bell",
    count: "2",
    year: "1950",
    shape: "bell",
    color: "white",
    size: "big",
    favorite: false,
  },
  {
    num: "10",
    name: "White ball retro",
    count: "7",
    year: "1960",
    shape: "ball",
    color: "white",
    size: "big",
    favorite: false,
  },
  {
    num: "11",
    name: "White spruce pine",
    count: "11",
    year: "1960",
    shape: "pine",
    color: "white",
    size: "small",
    favorite: false,
  },
  {
    num: "12",
    name: "White ball with flowers",
    count: "5",
    year: "1980",
    shape: "ball",
    color: "white",
    size: "big",
    favorite: false,
  },
  {
    num: "13",
    name: "Ball Painted River",
    count: "3",
    year: "1970",
    shape: "ball",
    color: "blue",
    size: "big",
    favorite: true,
  },
  {
    num: "14",
    name: "Ball Painted Village",
    count: "4",
    year: "1970",
    shape: "ball",
    color: "blue",
    size: "big",
    favorite: true,
  },
  {
    num: "15",
    name: "Painted bell",
    count: "3",
    year: "1970",
    shape: "bell",
    color: "blue",
    size: "medium",
    favorite: false,
  },
  {
    num: "16",
    name: "Painted pine cone Landscape",
    count: "3",
    year: "1970",
    shape: "pine",
    color: "blue",
    size: "medium",
    favorite: true,
  },
  {
    num: "17",
    name: "Painted pine cone",
    count: "7",
    year: "1970",
    shape: "pine",
    color: "red",
    size: "medium",
    favorite: false,
  },
  {
    num: "18",
    name: "Yellow ball with a bow",
    count: "2",
    year: "2010",
    shape: "ball",
    color: "yellow",
    size: "big",
    favorite: false,
  },
  {
    num: "19",
    name: "Yellow ball with sequins",
    count: "12",
    year: "1980",
    shape: "ball",
    color: "yellow",
    size: "big",
    favorite: false,
  },
  {
    num: "20",
    name: "Red ball with a bow",
    count: "8",
    year: "1950",
    shape: "ball",
    color: "red",
    size: "medium",
    favorite: true,
  },
  {
    num: "21",
    name: "Red ball with stars",
    count: "4",
    year: "1970",
    shape: "ball",
    color: "red",
    size: "big",
    favorite: true,
  },
  {
    num: "22",
    name: "Golden spruce pine",
    count: "11",
    year: "1990",
    shape: "pine",
    color: "yellow",
    size: "small",
    favorite: false,
  },
  {
    num: "23",
    name: "Old bell",
    count: "9",
    year: "1950",
    shape: "bell",
    color: "yellow",
    size: "big",
    favorite: false,
  },
  {
    num: "24",
    name: "Graceful snowflake",
    count: "1",
    year: "1940",
    shape: "snowflake",
    color: "white",
    size: "big",
    favorite: false,
  },
  {
    num: "25",
    name: "Pink ball with sequins",
    count: "12",
    year: "2010",
    shape: "ball",
    color: "red",
    size: "big",
    favorite: false,
  },
  {
    num: "26",
    name: "Ruby-gold ball",
    count: "8",
    year: "1960",
    shape: "ball",
    color: "yellow",
    size: "big",
    favorite: false,
  },
  {
    num: "27",
    name: "Red ball with pattern",
    count: "4",
    year: "2010",
    shape: "ball",
    color: "red",
    size: "big",
    favorite: false,
  },
  {
    num: "28",
    name: "Burgundy ball with a pattern",
    count: "10",
    year: "2010",
    shape: "ball",
    color: "red",
    size: "big",
    favorite: false,
  },
  {
    num: "29",
    name: "Old ball with flowers",
    count: "5",
    year: "1950",
    shape: "ball",
    color: "yellow",
    size: "big",
    favorite: true,
  },
  {
    num: "30",
    name: "Antique ball with a pattern",
    count: "8",
    year: "1950",
    shape: "ball",
    color: "yellow",
    size: "big",
    favorite: true,
  },
  {
    num: "31",
    name: "Red ball with sparkles",
    count: "8",
    year: "2010",
    shape: "ball",
    color: "red",
    size: "big",
    favorite: false,
  },
  {
    num: "32",
    name: "Blue Ball Universe",
    count: "11",
    year: "1970",
    shape: "ball",
    color: "blue",
    size: "big",
    favorite: false,
  },
  {
    num: "33",
    name: "Blue ball with snowflake",
    count: "6",
    year: "2010",
    shape: "ball",
    color: "blue",
    size: "medium",
    favorite: false,
  },
  {
    num: "34",
    name: "Green ball with a pattern",
    count: "8",
    year: "2010",
    shape: "ball",
    color: "green",
    size: "big",
    favorite: false,
  },
  {
    num: "35",
    name: "Figurine of a Fox in a scarf",
    count: "8",
    year: "1950",
    shape: "figure",
    color: "yellow",
    size: "medium",
    favorite: true,
  },
  {
    num: "36",
    name: "Lilac Ball Blizzard",
    count: "1",
    year: "2000",
    shape: "ball",
    color: "blue",
    size: "big",
    favorite: false,
  },
  {
    num: "37",
    name: "Green Ball Blizzard",
    count: "6",
    year: "2000",
    shape: "ball",
    color: "green",
    size: "big",
    favorite: false,
  },
  {
    num: "38",
    name: "Blue Ball Blizzard",
    count: "6",
    year: "2000",
    shape: "ball",
    color: "blue",
    size: "big",
    favorite: false,
  },
  {
    num: "39",
    name: "Red Snowflake",
    count: "6",
    year: "1990",
    shape: "snowflake",
    color: "red",
    size: "big",
    favorite: false,
  },
  {
    num: "40",
    name: "Golden snowflake",
    count: "12",
    year: "2020",
    shape: "snowflake",
    color: "yellow",
    size: "big",
    favorite: false,
  },
  {
    num: "41",
    name: "Arctic Snowflake",
    count: "11",
    year: "2020",
    shape: "snowflake",
    color: "white",
    size: "big",
    favorite: false,
  },
  {
    num: "42",
    name: "Green ball",
    count: "10",
    year: "1980",
    shape: "ball",
    color: "green",
    size: "medium",
    favorite: false,
  },
  {
    num: "43",
    name: "Two-color snowflake",
    count: "6",
    year: "1960",
    shape: "snowflake",
    color: "red",
    size: "big",
    favorite: false,
  },
  {
    num: "44",
    name: "Angel Figurine",
    count: "11",
    year: "1940",
    shape: "figure",
    color: "red",
    size: "medium",
    favorite: true,
  },
  {
    num: "45",
    name: `New Year"s snowflake`,
    count: "1",
    year: "1980",
    shape: "snowflake",
    color: "white",
    size: "big",
    favorite: false,
  },
  {
    num: "46",
    name: "Amanita figurine",
    count: "10",
    year: "1950",
    shape: "figure",
    color: "red",
    size: "small",
    favorite: false,
  },
  {
    num: "47",
    name: "Figurine Well",
    count: "6",
    year: "1950",
    shape: "figure",
    color: "red",
    size: "small",
    favorite: false,
  },
  {
    num: "48",
    name: "Yellow ball with a bow",
    count: "6",
    year: "1960",
    shape: "ball",
    color: "yellow",
    size: "big",
    favorite: false,
  },
  {
    num: "49",
    name: "Snowflake with turquoise",
    count: "4",
    year: "1980",
    shape: "snowflake",
    color: "yellow",
    size: "big",
    favorite: false,
  },
  {
    num: "50",
    name: "Big bell",
    count: "3",
    year: "2020",
    shape: "bell",
    color: "red",
    size: "big",
    favorite: false,
  },
  {
    num: "51",
    name: "Pine cone with frost",
    count: "12",
    year: "1970",
    shape: "pine",
    color: "red",
    size: "small",
    favorite: false,
  },
  {
    num: "52",
    name: "Red ball with an inscription",
    count: "12",
    year: "1990",
    shape: "ball",
    color: "red",
    size: "big",
    favorite: true,
  },
  {
    num: "53",
    name: "Silver snowflake",
    count: "6",
    year: "2020",
    shape: "snowflake",
    color: "white",
    size: "big",
    favorite: false,
  },
  {
    num: "54",
    name: "Green ball with a picture",
    count: "6",
    year: "2010",
    shape: "ball",
    color: "green",
    size: "big",
    favorite: false,
  },
  {
    num: "55",
    name: "Gingerbread House",
    count: "1",
    year: "1940",
    shape: "figure",
    color: "yellow",
    size: "big",
    favorite: false,
  },
  {
    num: "56",
    name: "Gingerbread House",
    count: "1",
    year: "1940",
    shape: "figure",
    color: "yellow",
    size: "small",
    favorite: false,
  },
  {
    num: "57",
    name: "Gingerbread House",
    count: "1",
    year: "1940",
    shape: "figure",
    color: "yellow",
    size: "medium",
    favorite: false,
  },
  {
    num: "58",
    name: "Polar bear figurine",
    count: "2",
    year: "1980",
    shape: "figure",
    color: "white",
    size: "medium",
    favorite: false,
  },
  {
    num: "59",
    name: "Yellow ball with an inscription",
    count: "10",
    year: "1990",
    shape: "ball",
    color: "yellow",
    size: "medium",
    favorite: false,
  },
  {
    num: "60",
    name: "Figurine Dove",
    count: "12",
    year: "1940",
    shape: "figure",
    color: "white",
    size: "medium",
    favorite: true,
  },
];
export default data;
