export const lightropes = [
  "lightrope-1",
  "lightrope-2",
  "lightrope-3",
  "lightrope-4",
  "lightrope-5",
  "lightrope-6",
  "lightrope-7",
  "lightrope-8",
  "lightrope-9",
  "lightrope-10",
  "lightrope-11",
];

export const lights = [
  ["odd-light", "even-light"],
  ["odd-light", "even-light", ""],
  ["odd-light", "even-light", "", "odd-light"],
  ["odd-light", "even-light", "", "odd-light", "even-light"],
  ["odd-light", "even-light", "", "odd-light", "even-light"],
  ["odd-light", "even-light", "", "odd-light", "even-light", ""],
  ["odd-light", "even-light", "", "odd-light", "even-light", "", "odd-light"],
  [
    "odd-light",
    "even-light",
    "",
    "odd-light",
    "even-light",
    "",
    "odd-light",
    "even-light",
  ],
  [
    "odd-light",
    "even-light",
    "",
    "odd-light",
    "even-light",
    "",
    "odd-light",
    "even-light",
    "",
  ],
  [
    "odd-light",
    "even-light",
    "",
    "odd-light",
    "even-light",
    "",
    "odd-light",
    "even-light",
    "",
  ],
  [
    "odd-light",
    "even-light",
    "",
    "odd-light",
    "even-light",
    "",
    "odd-light",
    "even-light",
    "",
  ],
];

export const flashes = [
  "flash-1",
  "flash-2",
  "flash-3",
  "flash-1",
  "flash-2",
  "flash-3",
  "flash-1",
  "flash-2",
  "flash-3",
];
